### PR TITLE
Fix remaining resources, build upon Pull Request #19.

### PR DESCRIPTION
**Pull request by kwilczynski**
This is to fix all of the resources that mutate the value that has been passed to them via the resource attribute uniformly (by making them use a common helper), making sure that when a Node attribute is passed they will not mutate the underlying value (otherwise an exception will be raised).

Signed-off-by: Krzysztof Wilczynski krzysztof.wilczynski@linux.com

### CODE REVIEW

**Comment by kwilczynski** [comment]
@nathwill this is to complement the work from #19. I should have corrected all of them before, apologies for overlooking this.

**Comment by nathwill** [comment]
Thanks @kwilczynski, looks great! I'll try to get this shipped before this weekend.

**Comment by nathwill** [comment]
ok, this is out in 1.1.0, thanks again!

**Comment by kwilczynski** [comment]
@nathwill much obliged!

**Pull request merged**
